# Generated by Django 5.0 on 2023-12-31 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
            ],
        ),
        migrations.CreateModel(
            name='DailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
                ('saturday_date', models.DateField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
            ],
        ),
    ]
