# Generated by Django 5.0 on 2023-12-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyincome',
            name='income',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
