# Generated by Django 5.0 on 2023-12-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dailyincome_income_alter_weeklyincome_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='income',
            new_name='value',
        ),
    ]
