# Generated by Django 5.0 on 2023-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_income_travel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyincome',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
